name: YAML Test
trigger:
  branches:
    include:
    - master
    exclude:
    - develop
jobs:
- job: FetchNupkgChange
  pool:
    name: Choco
  steps:
  - task: PowerShell@2
    name: NuspecSearch
    displayName: 'Get Nuspec Location'
  
  inputs:
    targetType: filePath
    filePath: ./search.ps1
    failOnStderr: true

  - task: PowerShell@2
      displayName: 'Run Pester Tests'
      name: Pester
    inputs:
      targetType: filePath
      filePath: ./build/pester.ps1

  - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      name: PublishTests
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '$(Package)*.XML'
      searchFolder: '$(Build.ArtifactStagingDirectory)'
      failTaskOnFailedTests: true

  - task: gep13.chocolatey-azuredevops.chocolatey-azuredevops.ChocolateyCommand@0
      displayName: 'Chocolatey pack'
      name: Pack
    inputs:
      packNuspecFileName: '$(NUSPECNAME)'

  - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      name: PublishArtifacts
    inputs:
      ArtifactName: '$(Package)'

- job: SubsequentA
  dependsOn: FetchNupkgChange
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: gep13.chocolatey-azuredevops.chocolatey-azuredevops.ChocolateyCommand@0
  displayName: 'Chocolatey install test'
  name: InstallTest
  inputs:
    command: install
    extraArguments: '-y'
    installPackageId: $[dependencies.FetchNupkgChange.outputs['NuspecSearch.Package']]
    installSource: '$(Build.ArtifactStagingDirectory)'
    installInstallArgs: '-'

- task: gep13.chocolatey-azuredevops.chocolatey-azuredevops.ChocolateyCommand@0
  displayName: 'Chocolatey Uninstall test'
  name: UninstallTest
  inputs:
    command: custom
    customCommand: uninstall
    customArguments: $[dependencies.Fetch.outputs['NuspecSearch.Package']]
