trigger:
  branches:
    include:
    - master
    exclude:
    - develop
jobs:
- job: Fetch
  pool:
    name: Choco

steps:
- - task: PowerShell@2
  displayName: 'Get Nuspec Location'
  name: NuspecSearch
  inputs:
    targetType: filePath
    filePath: ./search.ps1
    failOnStderr: true

- task: PowerShell@2
  displayName: 'Run Pester Tests'
  name: Pester
  inputs:
    targetType: filePath
    filePath: ./build/pester.ps1

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  name: PublishTests
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '$(Package)*.XML'
    searchFolder: '$(Build.ArtifactStagingDirectory)'
    failTaskOnFailedTests: true

- task: gep13.chocolatey-azuredevops.chocolatey-azuredevops.ChocolateyCommand@0
  displayName: 'Chocolatey pack'
  name: Pack
  inputs:
    packNuspecFileName: '$(NUSPECNAME)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  name: PublishArtifacts
  inputs:
    ArtifactName: '$(Package)'

- job: TestInstall
  dependsOn: Fetch
  pool:
    name: Hosted VS2017

- task: gep13.chocolatey-azuredevops.chocolatey-azuredevops.ChocolateyCommand@0
  displayName: 'Chocolatey install test'
  name: InstallTest
  inputs:
    command: install
    extraArguments: '-y'
    installPackageId: $[dependencies.Fetch.outputs['NuspecLocation.Package']]
    installSource: '$(Build.ArtifactStagingDirectory)'
    installInstallArgs: '-'

- task: gep13.chocolatey-azuredevops.chocolatey-azuredevops.ChocolateyCommand@0
  displayName: 'Chocolatey Uninstall test'
  name: UninstallTest
  inputs:
    command: custom
    customCommand: uninstall
    customArguments: '$(Package)'
