pool:
  name: Choco
trigger:
  branches:
    include:
    - master
    exclude:
    - develop
  pr: none
steps:
- task: PowerShell@2
  displayName: 'Get nuspec Location'
  inputs:
    targetType: 'inline'
    script: |
      write-host $pwd
      $changes = gci $pwd -Recurse -Include '*.nuspec','*.ps1' | ? { $_.LastWriteTime -gt (Get-Date).AddHours(-3) }
      
      If($changes.Count -gt 0) {
      $nuspecLocation =  ($changes | ? { $_.Extension -eq '.nuspec' -and $_.Directory}).DirectoryName
      $nuspec = (gci -Path $nuspecLocation -Filter '*.nuspec').FullName
      
      echo "##vso[task.setvariable variable=NUSPECLOCATION]$nuspecLocation"
      echo "##vso[task.setvariable variable=NUSPECNAME]$nuspec"
      
      }
      
      else { 
      
      throw "No suitable changes detected to build chocolatey package"
      }
    failOnStderr: true
- task: gep13.chocolatey-azuredevops.chocolatey-azuredevops.ChocolateyCommand@0
  displayName: 'Chocolatey pack'
  inputs:
    packNuspecFileName: $(NUSPECNAME)
- task: PowerShell@2
  displayName: 'Find nupkg'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host $pwd
      $Nupkg = (gci $pwd -Filter '*.nupkg').FullName
      Write-Host $Nupkg
      echo "##vso[task.setvariable variable=NupkgLocation]$Nupkg"
    failOnStderr: true
- task: gep13.chocolatey-azuredevops.chocolatey-azuredevops.ChocolateyCommand@0
  displayName: 'Chocolatey push'
  inputs:
    command: push
    pushNupkgFileName: $(NupkgLocation)
    pushSource: 'http://localhost:8081/artifactory/api/nuget/choco-local'
    pushApikey: $(ChocoApiKey)
    pushForce: true