pool:
  name: Choco
trigger:
  branches:
    include:
    - master
    exclude:
    - develop
steps:
- task: PowerShell@2
  displayName: 'Get nuspec Location'
  inputs:
    targetType: 'inline'
    script: |
      $changes = gci $pwd -Recurse -Include '*.nuspec','*.ps1' | ? { $_.LastWriteTime -gt (Get-Date).AddHours(-1) }
      
      If($changes.Count -gt 0) {
      $nuspecLocation =  ($changes | ? { $_.Extension -eq '.nuspec' -and $_.Directory}).DirectoryName
      $filter =  gci -Path $nuspecLocation -Filter '*.nuspec' | Select-Object FullName, BaseName
      $nuspec = $filter.Fullname
      $packageName = $filter.Basename
      echo "##vso[task.setvariable variable=NUSPECLOCATION]$nuspecLocation"
      echo "##vso[task.setvariable variable=NUSPECNAME]$nuspec"
      echo "##vso[task.setvariable variable=Package]$packageName"
      
      }
      
      else { 
      
      throw "No suitable changes detected to build chocolatey package"
      }
    failOnStderr: true
- task: gep13.chocolatey-azuredevops.chocolatey-azuredevops.ChocolateyCommand@0
  displayName: 'Chocolatey pack'
  inputs:
    packNuspecFileName: $(NUSPECNAME)
- task: PowerShell@2
  displayName: 'Find nupkg'
  inputs:
    targetType: 'inline'
    script: |
      $Nupkg = (gci $(Split-Path -Parent $pwd) -Recurse -Filter '*.nupkg').FullName
      echo "##vso[task.setvariable variable=NupkgLocation]$Nupkg"
    failOnStderr: true
- task: gep13.chocolatey-azuredevops.chocolatey-azuredevops.ChocolateyCommand@0
  displayName: 'Chocolatey push'
  inputs:
    command: push
    pushNupkgFileName: $(NupkgLocation)
    pushSource: 'http://localhost:8081/artifactory/api/nuget/choco-local'
    pushApikey: $(ChocoApiKey)
    pushForce: true
- task: gep13.chocolatey-azuredevops.chocolatey-azuredevops.ChocolateyCommand@0
  displayName: 'Verify Package'
  inputs:
    command: 'custom'
    customCommand: 'list'
    customArguments: '$(Package), -s http://localhost:8081/artifactory/api/nuget/choco-local'